test_access_ss_from_cloudbuild_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      dataset: example
      location: asia-northeast1
      threads: 8
      job_execution_timeout_seconds: 1200
      job_retries: 1
      priority: interactive
      scopes:
        - https://www.googleapis.com/auth/cloud-platform
        - https://www.googleapis.com/auth/bigquery
        - https://www.googleapis.com/auth/drive
        - https://www.googleapis.com/auth/spreadsheets
        - openid
        - https://www.googleapis.com/auth/userinfo.email
